# fly.toml app configuration file generated for tg-genshin-bot on 2023-11-06T02:40:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tg-genshin-bot"
primary_region = "ams"

[build]

[deploy]
  strategy = "immediate"